pipeline:
  name: deployment
  identifier: deployment
  projectIdentifier: manisha2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: customer
        identifier: customer
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: sgtest
                  identifier: sgtest
                  steps:
                    - step:
                        type: ShellScript
                        name: ShellScript_1
                        identifier: ShellScript_1
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo <+pipeline.stages.customer.type>
                                echo <+pipeline.stages.deploy.spec.deploymentType>
                                echo <+pipeline.stages.deploy.type>
                          environmentVariables: []
                          outputVariables: []
                        timeout: 15m
                  strategy:
                    repeat:
                      items:
                        - "18"
                        - "17"
                        - "16"
        tags: {}
    - stage:
        name: deploy
        identifier: deployed
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: rolloutsvcnew
          environment:
            environmentRef: dummy
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.deploy.spec.type>
                          echo <+pipeline.stages.deployed.spec.type>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: second
        identifier: second
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.deploy.spec.deploymentType>
                          echo <+pipeline.stages.deploy.type>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
